# Generated by Django 2.0.2 on 2018-02-04 22:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20180204_2217'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contactform',
            name='city',
        ),
        migrations.RemoveField(
            model_name='contactform',
            name='country',
        ),
        migrations.RemoveField(
            model_name='contactform',
            name='description',
        ),
        migrations.RemoveField(
            model_name='contactform',
            name='full_name',
        ),
        migrations.RemoveField(
            model_name='contactform',
            name='province_state',
        ),
    ]
